version: '3.9'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - ollama
    volumes:
      - .:/app

  mongodb:
    container_name: mongodb
    image: mongo:4.0
    ports:
      - "27017:27017"
    expose:
      - "27107"
    volumes:
      - ${MOUNTED_DATA}/mounted-data:/data/db/
    logging:
      driver: "none"
  ollama:
    image: ollama/ollama
    volumes:
      - ${MOUNTED_DATA}/ollama:/root/.ollama
    ports:
      - "11434:11434"
    expose:
     - "11434"

volumes:
  mongo-data:
